import type { components } from "../src/api/schema";

type Schema = components["schemas"];
export const health = { database: { schema_version: 2 }, qdrant: { available: true, memories: 1, raw: 1, error: null }, embedder: { ready: true, device: "cpu", revision: "revision" }, outbox: { pending: 0 }, jobs: {} } satisfies Schema["AdminHealthOut"];
export const scope = { id: "alice-space", slug: "alice", name: "Alice", kind: "user", writable: true } satisfies Schema["ScopeView"];
export const me = { id: "alice-id", handle: "alice", display_name: "Alice", role: "admin", auth_kind: "session", own_entity_id: scope.id, team_entity_id: null, scopes: [scope] } satisfies Schema["PrincipalView"];
export const memory = { id: "m1", text: "Use pnpm for this project", kind: "preference", context: {}, tags: [], source_role: "user", status: "active", review_status: "pending", importance: 0.6, confidence: 0.9, revision: 1, scope: "Alice", scope_slug: "alice", subject: null, subject_slug: null, author: "Alice", created_at: "2026-09-20T00:00:00Z", updated_at: "2026-09-20T00:00:00Z", valid_until: null, writable: true } satisfies Schema["MemoryRecord"];
export const metrics = { outbox_pending: 0, oldest_unprocessed_message: null, provider_errors: 0, month_spend_usd: 0, month_reserved_usd: 0, month_limit_usd: 100, pending_review: 0, search_latency_ms: { p50: 10, p95: 20, p99: 30 }, retrieval_runs: 1, abstention_rate: 0, feedback_labels: 0, feedback_runs: 0, useful_rate: null, correct_rate: null, spend_by_user: [], outbox_oldest_age_seconds: null, outbox_retries: 0, index_parity: { database_active: 1, qdrant_active: 1 }, backup_freshness_seconds: 60 } satisfies Schema["MetricsOut"];
export const reviewStats = { from: "2026-09-01T00:00:00Z", to: "2026-09-20T00:00:00Z", bucket: "day", totals: { pending: 0, oldest_pending: null, pending_by_source: {}, attention_by_kind: {} }, series: [] } satisfies Schema["ReviewStatsOut"];
export const searchResult = { retrieval_id: "run-1", memories: [{ ...memory, score: 0.9, similarity: 0.8, lexical: 1, entity: 0, recency: 0.5 }], raw: [], used_tokens: 5, policy_id: "neutral-v1", timings: { total_ms: 12 }, embed_ms: 2, dropped_trust: [], dropped_filter: [], dropped_validity: [], dropped_relevance: [] } satisfies Schema["MemorySearchOut"];
export const backups = { items: [{ id: "00000000-0000-4000-8000-000000000001", kind: "daily", path: "/backups/daily", sha256: "abc", bytes: 123, created_at: memory.created_at, verified_at: memory.created_at, protected: true }] } satisfies Schema["BackupsOut"];
export const judge = { id: 1, kind: "extraction", model: "model", prompt_version: "v1", input: { messages: ["Use pnpm"] }, output: { memories: [{ text: "Use pnpm" }] }, error: null, input_tokens: 10, output_tokens: 5, cost_usd: 0.001, latency_ms: 20, created_at: memory.created_at } satisfies Schema["JudgeRunOut"];
export const session = { id: "session-1", user: "alice", scope: "Alice", scope_slug: "alice", agent_id: "claude-code", started_at: memory.created_at, ended_at: null, context: {}, messages: 7, extracted: 3 } satisfies Schema["SessionView"];
